name: weatherinx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  retrofit: ^4.4.2
  get_storage: ^2.1.1
  getwidget: any
  logger: ^2.5.0
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  lottie: ^3.3.1
  weatherapi: ^1.1.0
  syncfusion_flutter_gauges: ^28.2.9
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.10.1
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  flutter_staggered_animations: ^1.1.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  fluttertoast: ^8.2.12
  package_info_plus: ^8.3.0
  weather_icons: ^3.0.0
  dynamic_color: ^1.7.0
  fl_chart: ^0.70.2
  animations: ^2.0.11
  skeletonizer: ^1.4.3
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0
  flutter_native_splash: ^2.4.5

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/